### ISSUE TITLE
ambiguous return

### ISSUE THREAD

**Issue by xbdeng** [NewbieOrange/SUSTech-SQL-Project2-Public#9]
When call function `EnrollResult enrollCourse(int studentId, int sectionId);`

If the student `ALREADY_SELECTED` or  `COURSE_IS_FULL`  or  `ALREADY_PASSED`  which one should I return?

These errors can happen at the same time.

**Comment by NewbieOrange** [comment]
The priority of `EnrollResult` should be:

`COURSE_NOT_FOUND` > `ALREADY_SELECTED` / `ALREADY_PASSED` > `PREREQUISITES_NOT_FULFILLED` > `COURSE_CONFLICT_FOUND` > `COURSE_IS_FULL` > `UNKNOWN_ERROR`

**Comment by NewbieOrange** [comment]
Note that since we have `StudentService#addEnrolledCourseWithScore(int studentId, int sectionId, @Nullable Short score)`, it is possible for a student-course have `ALREADY_SELECTED` **and** `ALREADY_PASSED` or `PREREQUISITES_NOT_FULFILLED`. Please make sure the return priority is the same as above in similar cases.
